# Generated by Django 6.0.7 on 2026-07-27 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nom utilisateur')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], default='client', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('entreprise', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entreprise')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ville', models.CharField(max_length=200, verbose_name='Ville')),
                ('service_souhaite', models.CharField(choices=[('energie_solaire', 'Énergie Solaire'), ('electricite_generale', 'Électricité Générale'), ('reseau_informatique', 'Réseau Informatique'), ('videosurveillance', 'Vidéosurveillance'), ('controle_acces', "Contrôle d'Accès"), ('securite_incendie', 'Sécurité Incendie'), ('cloture_electrique', 'Clôture Électrique'), ('telephonie_ip', 'Téléphonie IP'), ('maintenance', 'Maintenance Technique'), ('autre', 'Autre')], max_length=50, verbose_name='Service souhaité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du projet')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget estimé')),
                ('date_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='devis_pieces/', verbose_name='Pièce jointe')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('contacte', 'Contacté'), ('devis_envoye', 'Devis envoyé'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_devis', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-date_creation'],
            },
        ),
    ]
